import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar";
import Link from "next/link";
import { AppProvider } from "./context/AppContext";
import Header from "./Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon.png" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#2563eb" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="FastPanel" />
        <meta name="apple-mobile-web-app-title" content="FastPanel" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProvider>
          <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 flex">
            <Sidebar />
            <div className="flex-1 flex flex-col min-h-screen ml-0 md:ml-64 bg-transparent w-full">
              <Header />
              <main className="w-full flex-1 flex flex-col space-between">{children}</main>
              <footer className="bg-white shadow py-3 px-8 text-center text-gray-400 text-sm mt-8 w-full">
                FastPanel &copy; {new Date().getFullYear()} &mdash; Powered by Eligapris
              </footer>
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
